list/urls.py
from django.urls import path

from list.views import (
    TagListView,
    TagCreateView,
    TagDetailView,
    TagUpdateView,
    TagDeleteView,
    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    CompleteOrUndoTaskView,
)

urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path("tasks/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/detail/", TagDetailView.as_view(), name="tag-detail"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
    path(
        "tasks/<int:pk>/complete-undo/",
        CompleteOrUndoTaskView.as_view(),
        name="task-complete-undo",
    ),
]


app_name = "list"

todo_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(("list.urls", "list"), namespace="list")),
    path("__debug__/", include("debug_toolbar.urls")),
]

list/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=40, unique=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    completed = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, blank=True, related_name="tasks")

    class Meta:
        ordering = ["completed", "-created_at"]

    def __str__(self):
        return self.content

list/forms.py
from django import forms

from list.models import Task, Tag


class TaskCreateOrUpdateForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = "__all__"

        widgets = {
            "deadline": forms.DateTimeInput(
                attrs={"class": "form-control", "type": "datetime-local"}
            ),
            "tags": forms.CheckboxSelectMultiple(),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name != "tags":
                field.widget.attrs["class"] = "form-control mb-3"
        self.fields["completed"].widget.attrs["class"] = "form-check-input ml-3"


class TagCreateOrUpdateForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = "__all__"
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control mb-3"}),
        }

list/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import generic

from list.forms import TaskCreateOrUpdateForm, TagCreateOrUpdateForm
from list.models import Tag, Task


class TagListView(LoginRequiredMixin, generic.ListView):
    model = Tag
    template_name = "list/tag_list.html"
    paginate_by = 12


class TagDetailView(LoginRequiredMixin, generic.DetailView):
    model = Tag
    template_name = "list/tag_detail.html"
    paginate_by = 5
    queryset = Tag.objects.prefetch_related("tasks__tags")


class TagCreateView(LoginRequiredMixin, generic.edit.CreateView):
    model = Tag
    form_class = TagCreateOrUpdateForm
    template_name = "list/generic_form.html"
    success_url = reverse_lazy("list:tag-list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Create Tag"
        return context


class TagUpdateView(LoginRequiredMixin, generic.edit.UpdateView):
    model = Tag
    form_class = TagCreateOrUpdateForm
    template_name = "list/generic_form.html"
    success_url = reverse_lazy("list:tag-list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Update Tag"
        return context


class TagDeleteView(LoginRequiredMixin, generic.edit.DeleteView):
    model = Tag
    template_name = "list/confirm_delete.html"
    success_url = reverse_lazy("list:tag-list")


class TaskListView(LoginRequiredMixin, generic.ListView):
    model = Task
    template_name = "list/task_list.html"
    queryset = Task.objects.prefetch_related("tags")
    paginate_by = 5


class TaskCreateView(LoginRequiredMixin, generic.edit.CreateView):
    model = Task
    form_class = TaskCreateOrUpdateForm
    queryset = Task.objects.prefetch_related("tags")
    template_name = "list/generic_form.html"
    success_url = reverse_lazy("list:task-list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Create Task"
        return context


class TaskUpdateView(LoginRequiredMixin, generic.edit.UpdateView):
    model = Task
    form_class = TaskCreateOrUpdateForm
    queryset = Task.objects.prefetch_related("tags")
    template_name = "list/generic_form.html"
    success_url = reverse_lazy("list:task-list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Update Task"
        return context


class TaskDeleteView(LoginRequiredMixin, generic.edit.DeleteView):
    model = Task
    template_name = "list/confirm_delete.html"
    success_url = reverse_lazy("list:task-list")


class CompleteOrUndoTaskView(LoginRequiredMixin, generic.View):
    def post(self, request, pk):
        task = get_object_or_404(Task, pk=pk)
        task.completed = not task.completed
        task.save()
        return redirect("list:task-list")

templates/base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Todo list</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
  {% load static %}
</head>
<body>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3">
      {% block sidebar %}
        {% include "includes/sidebar.html" %}
      {% endblock %}
    </div>
    <div class="col-sm-9">
      {% block content %}
      {% endblock %}
      <div class="d-flex justify-content-center mt-4">
        {% block pagination %}
          {% include "includes/pagination.html" %}
        {% endblock %}
      </div>
    </div>
  </div>
</div>
</body>
</html>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<div class="container mt-4">
  <div class="list-group">
    <a href="{% url "list:task-list" %}" class="list-group-item list-group-item-action">Home</a>
    <a href="{% url "list:tag-list" %}" class="list-group-item list-group-item-action">Tags</a>
  </div>
</div>

templates/list/confirm_delete.html
{% extends "base.html" %}
{% block content %}
  <h1>Delete {{ object_name }}</h1>
  <p>Are you sure you want to delete?</p>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-danger">
    <a class="btn" href="{% url "list:task-list" %}">Cancel</a>
  </form>
{% endblock %}

templates/list/generic_form.html
{% extends "base.html" %}
{% block content %}
  <div class="container col-md-6">
    <h1 class="text-center mb-3">{{ title }}</h1>
    <form method="post" enctype="multipart/form-data" class="needs-validation" novalidate>
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  </div>
{% endblock %}

templates/list/tag_detail.html
{% extends "base.html" %}
{% block content %}
  <h3>All tasks for tag: {{ tag }}</h3>
  {% for task in tag.tasks.all %}
    <div class="list-group-item list-group-item-action flex-column align-items-start mb-3">
      <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1">{{ task.content }}</h5>
        <small>{{ task.created_at }}</small>
      </div>
      <p class="mb-1">
        {% if task.completed %}
          <span class="badge bg-success">Done</span>
        {% else %}
          <span class="badge bg-danger">Not done</span>
        {% endif %}
      </p>
      {% if task.deadline %}
        <p class="mb-1"><small>Deadline: {{ task.deadline }}</small></p>
      {% endif %}
      {% if task.tags.all %}
        <p class="mb-0">
          <small>Tags:
            {% for tag in task.tags.all %}
              <span class="badge bg-secondary">{{ tag }}</span>
            {% endfor %}
          </small>
        </p>
      {% endif %}
      <div class="d-flex justify-content-between mt-2">
        <div>
          <a href="{% url "list:task-update" pk=task.id %}" class="btn btn-warning btn-sm me-2">Update</a>
          <a href="{% url "list:task-delete" pk=task.id %}" class="btn btn-danger btn-sm me-2">Delete</a>
        </div>
        <div>
          {% if task.completed %}
            <form action="{% url "list:task-complete-undo" pk=task.id %}" method="post" style="display:inline;">
              {% csrf_token %}
              <button type="submit" class="btn btn-secondary btn-sm">Undo</button>
            </form>
          {% else %}
            <form action="{% url "list:task-complete-undo" pk=task.id %}" method="post" style="display:inline;">
              {% csrf_token %}
              <button type="submit" class="btn btn-success btn-sm">Complete</button>
            </form>
          {% endif %}
        </div>
      </div>
    </div>
  {% empty %}
    <h5>No tasks yet</h5>
  {% endfor %}
{% endblock %}

templates/list/tag_list.html
{% extends "base.html" %}
{% block content %}
<div class="container mt-4">
  <div class="d-flex justify-content-between align-items-center mb-3">
    <h3>Tags</h3>
    <a href="{% url "list:tag-create" %}" class="btn btn-primary">Create</a>
  </div>

  <div class="row">
    {% for tag in tag_list %}
      <div class="col-md-4 mb-3">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title"><a href="{% url "list:tag-detail" pk=tag.id %}">{{ tag.name }}</a></h5>
            <div class="d-flex justify-content-between">
              <a href="{% url "list:tag-update" pk=tag.id %}" class="btn btn-warning btn-sm">Update</a>
              <a href="{% url "list:tag-delete" pk=tag.id %}" class="btn btn-danger btn-sm">Delete</a>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

templates/list/task_list.html
{% extends "base.html" %}
{% block content %}
  <div class="container mt-4">
    <div class="d-flex justify-content-between align-items-center mb-3">
      <h3>TODO List</h3>
      <a href="{% url "list:task-create" %}" class="btn btn-primary">Create</a>
    </div>

    <div class="list-group">
      {% for task in task_list %}
        <div class="list-group-item list-group-item-action flex-column align-items-start mb-3">
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">{{ task.content }}</h5>
            <small class="text-muted">{{ task.created_at }}</small>
          </div>
          <p class="mb-1">
            {% if task.completed %}
              <span class="badge bg-success">Done</span>
            {% else %}
              <span class="badge bg-danger">Not done</span>
            {% endif %}
          </p>
          {% if task.deadline %}
            <p class="mb-1"><small>Deadline: {{ task.deadline }}</small></p>
          {% endif %}
          {% if task.tags.all %}
            <p class="mb-0">
              <small>Tags:
                {% for tag in task.tags.all %}
                  <span class="badge bg-secondary"><a style="text-decoration: none; color: white"
                                                      href="{% url "list:tag-detail" pk=tag.id %}">{{ tag }}</a></span>
                {% endfor %}
              </small>
            </p>
          {% endif %}
          <div class="d-flex justify-content-between align-items-center mt-2">
            <div>
              <a href="{% url 'list:task-update' pk=task.id %}" class="btn btn-warning btn-sm me-2">Update</a>
              <a href="{% url 'list:task-delete' pk=task.id %}" class="btn btn-danger btn-sm me-2">Delete</a>
            </div>
            <div>
              {% if task.completed %}
                <form action="{% url "list:task-complete-undo" pk=task.id %}" method="post" style="display:inline;">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-secondary btn-sm">Undo</button>
                </form>
              {% else %}
                <form action="{% url "list:task-complete-undo" pk=task.id %}" method="post" style="display:inline;">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-success btn-sm">Complete</button>
                </form>
              {% endif %}
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}